#!/usr/bin/env bash
# eec a scp command with positional params
fp = $1
uname = $2
ip = $3


if [$# -ne 4];
then
    echo"sage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KE"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi

