#!/usr/bin/env bash
#install Nginx
sudo apt-get -y update
sudo apt-get -y install  nginx
sudo chown  $USER:$USER /var/www/html/index.html
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

