#!/usr/bin/env bash
#install Nginx
sudo apt-get -y update
sudo apt-get -y install  nginx
sudo systemctl disable nginx
sudo echo "Hello World" > sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start

