#!/usr/bin/env bash
#make nginx listen on 8080,
#same as previous task but without nnginx user
chmod ugo+wrx /etc/nginx/nginx.conf
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart