#!/usr/bin/env bash
#make nginx listen on 8080
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod ugo+wrx /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
